"""Initial migration for PostgreSQL

Revision ID: 081fbdd6cb20
Revises: 50b1ea6e1aa2
Create Date: 2026-02-21 12:31:43.086395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081fbdd6cb20'
down_revision: Union[str, Sequence[str], None] = '50b1ea6e1aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
