"""add orders and order_items

Revision ID: 2ab1b0be9975
Revises: acc356061038
Create Date: 2026-03-02 13:24:52.404614

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ab1b0be9975"
down_revision: Union[str, Sequence[str], None] = "acc356061038"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("payment_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_unique_constraint(None, "orders", ["payment_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="unique")
    op.drop_column("orders", "paid_at")
    op.drop_column("orders", "payment_id")
    # ### end Alembic commands ###
